# site settings
title: AI4HEALTH
subtitle: by Dagger Stark
email: daggerstark0@gmail.com
description: Employing Machine Learning (ML) and Deep Learning (DL) for good and solving some challenging healthcare related problems!
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: San Diego
state: CA
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 1

# social settings
500px_url:
facebook_url:
github_url:
researchgate_url: 
gitlab_url: https://github.com/daggerstark
googlescholar_url: 
googleplus_url: 
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# Google Analytics
google_analytics: 

# build settings
markdown: kramdown

sass:
  style: compressed
