# site settings
title: Shivam Raval
subtitle: 
email: daggerstark0@gmail.com
description: 
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: New York
state: NY
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: # accepts "posts" or "pages"
tiles-count: 

# social settings
500px_url:
facebook_url:
github_url:
researchgate_url: 
gitlab_url: https://github.com/daggerstark
googlescholar_url: 
googleplus_url: 
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# Google Analytics
google_analytics: 

# build settings
markdown: kramdown

sass:
  style: compressed
